# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

resources:
 pipelines:
     - pipeline: my_pipeline1
       source: anukritigupta1234.hello-world
       trigger: true

pool: default

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- checkout: my_pipeline1

# - task: DownloadGitHubRelease@0
#   displayName: 'Download GitHub Release'
#   inputs:
#     connection: 'github'
#     userRepository: 'anukritigupta1234/test'
