# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  repositories:
    - repository: MyRepo1
      type: github
      endpoint: github_1
      name: anukritigupta1234/test
      

trigger:
- master

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: MyRepo1


